from detectron2.config import CfgNode as CN

def add_custom_config(cfg):
    cfg.MODEL.WEIGHTS = ""

    cfg.MODEL.BACKBONE = CN()
    cfg.MODEL.BACKBONE.NAME = ""
    cfg.MODEL.BACKBONE.NUM_FEATURES = [128, 256, 512, 1024]
    cfg.MODEL.BACKBONE.FEATURE_KEYS = ["res2", "res3", "res4", "res5"]

    cfg.MODEL.SWIN = CN()
    cfg.MODEL.SWIN.PRETRAIN_IMG_SIZE = 224
    cfg.MODEL.SWIN.PATCH_SIZE = 4
    cfg.MODEL.SWIN.EMBED_DIM = 96
    cfg.MODEL.SWIN.DEPTHS = [2, 2, 6, 2]
    cfg.MODEL.SWIN.NUM_HEADS = [3, 6, 12, 24]
    cfg.MODEL.SWIN.WINDOW_SIZE = 7
    cfg.MODEL.SWIN.MLP_RATIO = 4.0
    cfg.MODEL.SWIN.QKV_BIAS = True
    cfg.MODEL.SWIN.QK_SCALE = None
    cfg.MODEL.SWIN.DROP_RATE = 0.0
    cfg.MODEL.SWIN.ATTN_DROP_RATE = 0.0
    cfg.MODEL.SWIN.DROP_PATH_RATE = 0.3
    cfg.MODEL.SWIN.APE = False
    cfg.MODEL.SWIN.PATCH_NORM = True
    cfg.MODEL.SWIN.OUT_FEATURES = ["res2", "res3", "res4", "res5"]
    cfg.MODEL.SWIN.USE_CHECKPOINT = False

    cfg.MODEL.NECK = CN()
    cfg.MODEL.NECK.DIM = 256

    cfg.MODEL.IOR_DECODER = CN()
    cfg.MODEL.IOR_DECODER.EMBED_DIM = 256

    cfg.MODEL.IOR_DECODER.INSTANCE_SEG = CN()
    cfg.MODEL.IOR_DECODER.INSTANCE_SEG.NUM_QUERIES = 256
    cfg.MODEL.IOR_DECODER.INSTANCE_SEG.NUM_BLOCKS = 4

    cfg.MODEL.IOR_DECODER.IOR_ENCODER = CN()
    cfg.MODEL.IOR_DECODER.IOR_ENCODER.NUM_IOR_POINTS = 256
    cfg.MODEL.IOR_DECODER.IOR_ENCODER.NUM_TOKENS = 20
    cfg.MODEL.IOR_DECODER.IOR_ENCODER.NUM_BLOCKS = 2

    cfg.MODEL.IOR_DECODER.IOR_ENCODER.ADDIOR = CN()
    cfg.MODEL.IOR_DECODER.IOR_ENCODER.ADDIOR.NUM_BLOCKS = 4

    cfg.MODEL.IOR_DECODER.CROSSATTN = CN()
    cfg.MODEL.IOR_DECODER.CROSSATTN.NUM_HEADS = 8
    cfg.MODEL.IOR_DECODER.CROSSATTN.DROPOUT = 0.0

    cfg.MODEL.IOR_DECODER.FFN = CN()
    cfg.MODEL.IOR_DECODER.FFN.HIDDEN_DIM = 1024
    cfg.MODEL.IOR_DECODER.FFN.DROPOUT = 0.0

    cfg.MODEL.IOR_DECODER.MASK_DECODER = CN()
    cfg.MODEL.IOR_DECODER.MASK_DECODER.NUM_BLOCKS = 4

    cfg.MODEL.IOR_DECODER.LEARNABLE_PE = CN()
    cfg.MODEL.IOR_DECODER.LEARNABLE_PE.HEIGHT = 32
    cfg.MODEL.IOR_DECODER.LEARNABLE_PE.WIDTH = 32

    cfg.DATASETS.ROOT = ""

    cfg.SOLVER.BACKBONE_MULTIPLIER = 0.1
    cfg.SOLVER.OPTIMIZER = "ADAMW"
    cfg.SOLVER.WEIGHT_DECAY_EMBED = 0.0
    
    cfg.TEST.AUG = CN()
    cfg.TEST.AUG.ENABLED = False
    cfg.TEST.UTMOST_OBJECTS = 20
    cfg.TEST.METRICS_OF_INTEREST = ["mae"]
    cfg.TEST.THRESHOLD = 0.5

    cfg.INPUT.FT_SIZE_TRAIN = 800
    cfg.INPUT.FT_SIZE_TEST = 800

    cfg.OUTPUT_DEBUG = "output/debug/"
    cfg.OUTPUT_EVAL = "output/eval"
    cfg.EVAL_SAVE = False