MODEL:
    META_ARCHITECTURE: "SRNet"
    PIXEL_MEAN: [123.675, 116.280, 103.530]
    PIXEL_STD: [58.395, 57.120, 57.375]
    WEIGHTS: ""
    PE: "APE"
    BACKBONE:
        NAME: "ResNeXt50"
        NUM_FEATURES: (256,512,1024,2048)
        FEATURE_KEYS: ["res2", "res3", "res4", "res5"]
    NECK:
        NAME: "FrcPN"
    SIS_HEAD:
        NAME: "FovealQSADeep"
        NUM_BLOCKS: 6
        KEY_FEATURES: ["res5", "res4", "res3"]
        MASK_KEY: "res2"
    GAZE_SHIFT_HEAD:
        NAME: "CenterSoftMax"
        NUM_BLOCKS: 6
        SIGMA: 10.0
        KERNEL_SIZE: 5
        ALPHA: 1.0
        KEY: "res5"
    COMMON:
        EMBED_DIM: 256
        NUM_HEADS: 8
        HIDDEN_DIM: 2048
        DROPOUT_ATTN: 0.0
        DROPOUT_FFN: 0.0
        NUM_QUERIES: 100
LOSS:
    CLS_COST: 2.0
    MASK_CE_COST: 5.0
    MASK_DICE_COST: 5.0
    BBOX_L1_COST: 5.0
    BBOX_GIOU_COST: 2.0
    SAL_COST: 5.0
    OBJ_POS: 1.0
    OBJ_NEG: 0.1
    AUX_WEIGHT: 0.4
    AUX: "enable"
DATASETS:
    TRAIN: ("assr_train",)
    TEST: ("assr_test",)
    ENV:
        WORK: "D:/SaliencyRanking/dataset/coco_sor"
        GROUP4090: "/home/ryn02/hkguan/saliencyranking/dataset/coco_sor"
        BURGUNDY: "/home/huankguan2/saliencyranking/dataset/coco_sor"
        HTGC: "/home/grads/huankguan2/projects/saliencyranking/dataset/coco_sor"
        GROUP3090: "/home/luke/dataset/SOR_RANK/coco_sor"
    ROOT: "datasets"
DATALOADER:
    NUM_WORKERS: 8
SOLVER:
    AMP:
        ENABLED: true
    BACKBONE_MULTIPLIER: 1.0
    BASE_LR: 0.0001
    CHECKPOINT_PERIOD: 5000
    CLIP_GRADIENTS:
        CLIP_TYPE: full_model
        CLIP_VALUE: 0.01
        ENABLED: true
        NORM_TYPE: 2.0
    GAMMA: 0.1
    IMS_PER_BATCH: 32
    IMS_PER_GPU: 8
    LR_SCHEDULER_NAME: WarmupMultiStepLR
    MOMENTUM: 0.9
    OPTIMIZER: ADAMW
    STEPS: (10000,10001)
    MAX_ITER: 10002
    REFERENCE_WORLD_SIZE: 0
    WARMUP_FACTOR: 1.0
    WARMUP_ITERS: 100
    WEIGHT_DECAY: 0.0001
INPUT:
    FT_SIZE_TRAIN: 800
    FT_SIZE_TEST: 800
    MIN_SIZE_TRAIN: (480,640)
    MIN_SIZE_TEST: 640
    MAX_SIZE_TEST: 1333
    FORMAT: "RGB"
OUTPUT_DIR: "output/srnet"
TEST:
    EVAL_PERIOD: 5000
    METRICS_OF_INTEREST: ["mae", "acc", "fbeta", "iou", "sa_sor", "sor", "ap", "ar", "top1", "top2", "top3", "top4", "top5"]
    THRESHOLD: 0.5
    EXPECTED_RESULTS: []
    PRECISE_BN:
        ENABLED: false
        NUM_ITER: 200
    AUG:
        ENABLED: false
    UPPER_BOUND: false
    EVAL_SAVE: false
VERSION: 2
