MODEL:
    META_ARCHITECTURE: "SRDetr"
    PIXEL_MEAN: [123.675, 116.280, 103.530]
    PIXEL_STD: [58.395, 57.120, 57.375]
    BACKBONE:
        NAME: "D2SwinTransformer"
        NUM_FEATURES: (128,256,512,1024)
        FEATURE_KEYS: ["res2", "res3", "res4", "res5"]
    SWIN:
        EMBED_DIM: 128
        DEPTHS: [2, 2, 18, 2]
        NUM_HEADS: [4, 8, 16, 32]
        WINDOW_SIZE: 12
        APE: False
        DROP_PATH_RATE: 0.3
        PATCH_NORM: True
        PRETRAIN_IMG_SIZE: 384
        OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    NECK:
        DIM: 256
    IOR_DECODER:
        EMBED_DIM: 256
        IOR_ENCODER:
            NUM_IOR_POINTS: 256
            NUM_TOKENS: 20
            NUM_BLOCKS: 2
        INSTANCE_SEG:
            NUM_QUERIES: 50
            NUM_BLOCKS: 4
        ADDIOR:
            NUM_BLOCKS: 4
        MASK_DECODER:
            NUM_BLOCKS: 4
        CROSSATTN:
            NUM_HEADS: 8
            DROPOUT: 0.0
        FFN:
            HIDDEN_DIM: 1024
            DROPOUT: 0.1
        LEARNABLE_PE:
            WIDTH: 32
            HEIGHT: 32
    WEIGHTS: "pretrained/swin_base_patch4_window12_384_22k.pth"
DATASETS:
    TRAIN: ("assr_train",)
    TEST: ("assr_test",)
    ROOT: "/home/luke/dataset/SOR_RANK/coco_sor"
DATALOADER:
    NUM_WORKERS: 4
SOLVER:
    AMP:
        ENABLED: true
    BACKBONE_MULTIPLIER: 0.1
    BASE_LR: 0.00001
    CHECKPOINT_PERIOD: 5000
    CLIP_GRADIENTS:
        CLIP_TYPE: full_model
        CLIP_VALUE: 0.01
        ENABLED: true
        NORM_TYPE: 2.0
    GAMMA: 0.1
    IMS_PER_BATCH: 16
    LR_SCHEDULER_NAME: WarmupMultiStepLR
    MOMENTUM: 0.9
    OPTIMIZER: ADAMW
    STEPS: (95000, 98000)
    MAX_ITER: 100000
    REFERENCE_WORLD_SIZE: 0
    WARMUP_FACTOR: 1.0
    WARMUP_ITERS: 10
    WARMUP_METHOD: linear
INPUT:
    FT_SIZE_TRAIN: 1024
    FT_SIZE_TEST: 1024
    MIN_SIZE_TRAIN: (480,640)
    MIN_SIZE_TEST: 640
    MAX_SIZE_TEST: 1333
    FORMAT: "RGB"
OUTPUT_DIR: "output/"
OUTPUT_DEBUG: "output/debug/"
OUTPUT_EVAL: "output/eval"
EVAL_SAVE: false
TEST:
    EVAL_PERIOD: 5000
    UTMOST_OBJECTS: 5
    METRICS_OF_INTEREST: ["mae", "acc", "fbeta", "iou", "sa_sor", "sor", "ap", "ar", "top1"]
    THRESHOLD: 0.5
    EXPECTED_RESULTS: []
    PRECISE_BN:
        ENABLED: false
        NUM_ITER: 200
    AUG:
        ENABLED: false
    UPPER_BOUND: false
VERSION: 2
