_BASE_: swinB_384_22k.yaml
MODEL:
    PE: "SINE"
    SIS_HEAD:
        NAME: "Mask2Former"
        NUM_BLOCKS: 9
LOSS:
    OBJ_POS: 10.0
    OBJ_NEG: 0.1
    AUX_WEIGHT: 0.0
    AUX: "disable"
SOLVER:
    WEIGHT_DECAY: 0.05