_BASE_: swinB_384_22k.yaml
MODEL:
    META_ARCHITECTURE: "SRNetFull"
    PE: "APE"
    SIS_HEAD:
        NAME: "MultiQ"
        NUM_BLOCKS: 6
    GAZE_SHIFT_HEAD:
        NAME: "CenterShift"
        NUM_BLOCKS: 3
        KEY: "res5"
    MODULES:
        MULTIQ:
            GRID_SIZES: [[2,2], [3,3], [4,4]]
LOSS:
    OBJ_POS: 30.0
    OBJ_NEG: 0.1
    AUX_WEIGHT: 0.4
    AUX: "enable"
    SAL_TERMINATE: true
SOLVER:
    WEIGHT_DECAY: 0.0001