MODEL:
    META_ARCHITECTURE: "SRFovealSA"
    PIXEL_MEAN: [123.675, 116.280, 103.530]
    PIXEL_STD: [58.395, 57.120, 57.375]
    BACKBONE:
        NAME: "D2SwinTransformer"
        NUM_FEATURES: (128,256,512,1024)
        FEATURE_KEYS: ["res2", "res3", "res4", "res5"]
    SWIN:
        EMBED_DIM: 128
        DEPTHS: [2, 2, 18, 2]
        NUM_HEADS: [4, 8, 16, 32]
        WINDOW_SIZE: 12
        APE: False
        DROP_PATH_RATE: 0.3
        PATCH_NORM: True
        PRETRAIN_IMG_SIZE: 384
        OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    NECK:
        DIM: 256
        NUM_FEATURES: (256,512,1024)
        FEATURE_KEYS: ["res3", "res4", "res5"]
    MODULES:
        BBOX_DECODER:
            NUM_BLOCKS: 4
            NUM_QUERIES: 100
        MASK_DECODER:
            NUM_BLOCKS: 2
        GAZE_SHIFT:
            NUM_BLOCKS: 3
            SIGMA: 10.0
            KERNEL_SIZE: 5
            ALPHA: 1.0
            KEY: "res5"
        FOVEAL:
            NUM_BLOCKS: 6
            KEY_FEATURES: ["res5", "res4", "res3"]
        FOVEALQ:
            NUM_BLOCKS: 6
            KEY_FEATURES: ["res5", "res4", "res3"]
        FOVEALDYNAMIC:
            MERGE_NAME: "FovealStep"
            NUM_BLOCKS: 6
            KEY_FEATURES: ["res5", "res4", "res3"]
    COMMON:
        EMBED_DIM: 256
        NUM_HEADS: 8
        HIDDEN_DIM: 2048
        DROPOUT_ATTN: 0.0
        DROPOUT_FFN: 0.0
        NUM_QUERIES: 100
    WEIGHTS: "pretrained/swin_base_patch4_window12_384_22k.pth"
LOSS:
    WEIGHTS:
        CLS_COST: 1.0
        MASK_COST: 1.0
        BBOX_COST: 1.0
        SAL_COST: 5.0
        OBJ_POS: 30.0
        OBJ_NEG: 1.0
DATASETS:
    TRAIN: ("assr_train",)
    TEST: ("assr_test",)
    ENV:
        WORK: "D:/SaliencyRanking/dataset/coco_sor"
        GROUP4090: "/home/ryn02/hkguan/saliencyranking/dataset/coco_sor"
        BURGUNDY: "/home/huankguan2/saliencyranking/dataset/coco_sor"
        HTGC: "/home/grads/huankguan2/projects/saliencyranking/dataset/coco_sor"
        GROUP3090: "/home/luke/dataset/SOR_RANK/coco_sor"
    ROOT: "datasets"
DATALOADER:
    NUM_WORKERS: 16
SOLVER:
    AMP:
        ENABLED: true
    BACKBONE_MULTIPLIER: 1.0
    BASE_LR: 0.0001
    CHECKPOINT_PERIOD: 5000
    CLIP_GRADIENTS:
        CLIP_TYPE: full_model
        CLIP_VALUE: 0.01
        ENABLED: true
        NORM_TYPE: 2.0
    GAMMA: 0.1
    IMS_PER_BATCH: 32
    IMS_PER_GPU: 8
    LR_SCHEDULER_NAME: WarmupMultiStepLR
    MOMENTUM: 0.9
    OPTIMIZER: ADAMW
    STEPS: (20000,28000)
    MAX_ITER: 30000
    REFERENCE_WORLD_SIZE: 0
    WARMUP_FACTOR: 1.0
    WARMUP_ITERS: 100
    WEIGHT_DECAY: 0.0001
INPUT:
    FT_SIZE_TRAIN: 800
    FT_SIZE_TEST: 800
    MIN_SIZE_TRAIN: (480,640)
    MIN_SIZE_TEST: 640
    MAX_SIZE_TEST: 1333
    FORMAT: "RGB"
OUTPUT_DIR: "output/"
TEST:
    EVAL_PERIOD: 5000
    METRICS_OF_INTEREST: ["mae", "acc", "fbeta", "iou", "sa_sor", "sor", "ap", "ar", "top1", "top2", "top3", "top4", "top5"]
    THRESHOLD: 0.5
    EXPECTED_RESULTS: []
    PRECISE_BN:
        ENABLED: false
        NUM_ITER: 200
    AUG:
        ENABLED: false
    UPPER_BOUND: false
    EVAL_SAVE: false
VERSION: 2
