_BASE_: base_resnext50.yaml
MODEL:
    BACKBONE:
        NAME: "D2SwinTransformer"
        NUM_FEATURES: (128,256,512,1024)
        FEATURE_KEYS: ["res2", "res3", "res4", "res5"]
    SWIN:
        EMBED_DIM: 128
        DEPTHS: [2, 2, 18, 2]
        NUM_HEADS: [4, 8, 16, 32]
        WINDOW_SIZE: 12
        APE: False
        DROP_PATH_RATE: 0.3
        PATCH_NORM: True
        PRETRAIN_IMG_SIZE: 384
        OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    WEIGHTS: "pretrained/swin_base_patch4_window12_384_22k.pth"
    